services:
  client0:
    image: anel_em:0.1
    command: python3 -u client.py 0 no0 5000
    networks:
      - ring_network

  client1:
    image: anel_em:0.1
    command: python3 -u client.py 1 no1 5001
    networks:
      - ring_network

  client2:
    image: anel_em:0.1
    command: python3 -u client.py 2 no2 5002
    networks:
      - ring_network

  client3:
    image: anel_em:0.1
    command: python3 -u client.py 3 no3 5003

    networks:
      - ring_network

  client4:
    image: anel_em:0.1
    command: python3 -u client.py 4 no4 5004
    networks:
      - ring_network

networks:
  ring_network:
    driver: bridge
